### ISSUE TITLE
Handle boolean and/or toggle parameter

### ISSUE THREAD

**Issue by MartinHelmut** [krieselreihe/litr#10]
Sometimes you just want to activate/deactivate something based on a flag. This issue will serve to explore the how.

## First draft

```toml
[commands.name]
# Is using a ternary really the solution?
script = "cmake %{name1} ... %{name2 ? 'do this' : 'do that'}"

[params.name1]
type = "boolean"
default = false

[params.name2]
type = "boolean"
default = true
```

**Comment by MartinHelmut** [comment]
More thoughts, different syntax.

Only add if true:

```toml
[commands.build]
script = "cmake ${name 'do this'}"

[params.name]
type = "boolean"
```

If..else style with the `or` keyword:

```toml
[commands.build]
script = "cmake ${name 'do this' or 'do that'}"

[params.name]
type = "boolean"
```
