### ISSUE TITLE
Duplicated identifier report as syntax error in TOML configuration file

### ISSUE THREAD

**Issue by MartinHelmut** [krieselreihe/litr#27]
Given the following config example:

```toml
[commands]
test = "..."

[commands.test]
script = "..."
```

The following error will be produced:

```shell
Error:
4 | [commands.test]
  | ^ - There is a syntax error inside the configuration file.
```

This is not really helpful and should rather be explicit that an identifier was duplicated.
