### ISSUE TITLE
What if you could use parameters inside the directory option?

### ISSUE THREAD

**Issue by MartinHelmut** [krieselreihe/litr#34]
## Description

Given the following test script:

```toml
[commands.test]
dir = "build/%{target}/src/tests"
script = "cd build/%{target}/src/tests && ctest && ../../../.."
```

Allowing parameters inside the `dir` option could enable this change;

```toml
[commands.test]
dir = "build/%{target}/src/tests"
script = "ctest"
```

## Open questions

- Is this wanted / Should this work?
-  What are the implications for other command options?
