### ISSUE TITLE
Error message for missing required parameter on command execution

### ISSUE THREAD

**Issue by MartinHelmut** [krieselreihe/litr#35]
Currently running a command without a required parameter will print a wrong error (from the script parser). This should be catched with a proper user error e.g. "Running command XY requires the following parameter(s): ...".

Given the following configuration file:

```toml
[commands]
test = "cd build/%{target}/src/tests && ctest && cd ../../../.."

[params]
target = "Define the application build target."
```

The following calls need to be handled:

```shell
litr test
litr test --target
```
