### ISSUE TITLE
Parameters list not properly aligned inside help text

### ISSUE THREAD

**Issue by MartinHelmut** [krieselreihe/litr#53]
## Description

Given the following configuration:

```toml
[commands]
[commands.update]
script = "git pull && git fetch --prune && yarn"
description = "Update this repository."

[commands.open]
script = "openapp %{link}"
description = "Open an App link inside the running simulator."

[params.link]
shortcut = "l"
description = "Link to open inside the running App simulator."
```

The following help is generated:

```
Litr - Language Independent Task Runner [version 1.0.0-alpha.3]
  Configuration file found under: /.litr.toml

Usage: litr command [options]

Commands:
  open    --link=<option>
             Open an App link inside the running simulator.
  update     Update this repository to the latest and run install commands.

Options:
  -h --help  Show this screen.
  -v --version Show current Litr version.
  -l --link  Link to open inside the running App simulator.
```

## Problem

The parameters are not properly aligned inside the help text. They should all be 2 spaces after the version flag.
