### ISSUE TITLE
Running help for a specific command will not show the description for that command

### ISSUE THREAD

**Issue by MartinHelmut** [krieselreihe/litr#57]
## Description

Given the following configuration:

```toml
[commands.hello]
script = "..."
description = "Say hello."
```

Running:

```shell
litr hello --help
```

Will produce:

```
Litr - Language Independent Task Runner [version 1.0.0]
  Configuration file found under: /Path/to/litr.toml

Usage: litr hello [options]

Options:
  -h --help  Show this screen.
  -v --version Show current Litr version.
```

## Problem

The description is not sown.
