### ISSUE TITLE
Better error reporting for using wrong type on conditions

### ISSUE THREAD

**Issue by MartinHelmut** [krieselreihe/litr#60]
## Reproducing

Configuration:

```toml
[commands.hello]
script = "echo %{name 'Name'}"

[params.name]
description = "Say my name."
```

Running:

```shell
litr hello --name=true
```

Prints a duplicated, wrong error message:

```
Error: Problem parsing script!
  → /path/to/litr.toml
2 | script = "echo Hello %{name 'bob'}"
  |                                 └─ Cannot parse at `'bob'`: Expected `}`.
 ...
2 | script = "echo Hello %{name 'bob'}"
  |                                 └─ Cannot parse at `'bob'`: Expected `}`.
```

## Problem

This error message does not give any context what is wrong. it should point to using boolean parameters for condition, maybe even show how to fix this.
