### ISSUE TITLE
Color gets lost for underlying scripts

### ISSUE THREAD

**Issue by MartinHelmut** [krieselreihe/litr#64]
## Description

Running a script through Litr that emits colored output will remove the color. Though, it should be preserved.

## Reproduction

Configuration file:

```toml
[commands.test]
script = "printf 'Hello \033[0;31mWorld\033[0m\n'"
```

Run the following command:

```shell
litr test
```

## Expectations

The word "World" should be red, but isn't.
