### ISSUE TITLE
How to handle positional arguments

### ISSUE THREAD

**Issue by MartinHelmut** [krieselreihe/litr#7]
Currently the only way to pass values is via parameters. Explore the option for positional parameters. Here a very early first draft:

```toml
[commands.build]
script = "build some file ${0}"
```

As numbers are not allowed for parameter names they can be used to reference to a positional argument. To give more context to an argument:

```toml
[commands.build]
script = "build some file ${0}"
arguments = [
  { name = "file", description = "Something nice" } # Relates to ${0} 
]
```
