### ISSUE TITLE
Set search path / PATH variable from configuration

### ISSUE THREAD

**Issue by MartinHelmut** [krieselreihe/litr#77]
Would be nice to be able to set/extend search paths for easier command use. Assuming there is a "options" block supported in the config, the following could be possible (NPM example).

```toml
# litr.toml
[options]
paths = ["node_modules/.bin"]

[commands]
format = "prettier --write ."
```
